sudo: required
services:
    - docker

before_install:
    - docker build -t mmostetskyi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mmostetskyi/docker-react npm run test -- --coverage